title: Ruchir Ravishankar
logo: /assets/img/ruchir.jpg
description: Recent Master's Graduate in Aerospace Engineering
tagline: Seeking Full-time/Internship Opportunities
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Site Author
author:
  name             : "Ruchir Ravishankar"
  location         : #"Pale Blue Dot"
  email            : "ravishankarruchir@gmail.com"
  cv               : "assets/files/RuchirRavishankar_resume.pdf"
  googlescholar    : #
  github           : "https://github.com/rihcur"
  linkedin         : "https://www.linkedin.com/in/rihcur/"
  orcid            : #"https://orcid.org/0009-0000-2258-8827"
  ucresearchdirectory: #"https://researchdirectory.uc.edu/p/yasinaz"

github: [metadata]
